version: '2'
services:
  core1_d7:
    image: solr:6.6
    ports:
     - "8983:8983"
    volumes:
    - volume_core1_d7:/opt/solr/server/solr/mycores
  core2_d7:
    image: solr:6.6
    ports:
     - "8982:8982"
    volumes:
    - volume_core2_d7:/opt/solr/server/solr/mycores
  core1_d8:
    image: solr:6.6
    ports:
     - "8984:8984"
    volumes:
      - ./config/drupal8/core.properties:/opt/solr/server/solr/mycores/search/core.properties
      - ./config/drupal8/solr-6.x:/opt/solr/server/solr/mycores/search/conf
      - ./data:/opt/solr/server/solr/mycores/search/data
volumes:
  volume_core1_d7:
    external: true
